import type {
  LinkSuggestion,
  PostSummary,
  SettingsResponse,
  StatsResponse,
} from './client.ts';

export const mockData: {
  stats: StatsResponse;
  posts: PostSummary[];
  linkSuggestions: LinkSuggestion[];
  settings: SettingsResponse;
} = {
  stats: {
    posts_published: 12,
    pages_published: 4,
    avg_score: 78,
    schema_coverage: 92,
    internal_links_total: 48,
    orphan_pages: 2,
    posts_with_faq: 5,
    last_audit: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    score_trend: Array.from({ length: 14 }, (_, i) => ({
      date: new Date(Date.now() - (13 - i) * 86400000).toISOString().slice(0, 10),
      score: 55 + Math.round(Math.sin(i / 2) * 8 + i * 1.6 + Math.random() * 4),
    })),
  },
  posts: [
    {
      id: 4,
      title: 'What is GEO and why does it matter?',
      url: 'http://localhost:8080/what-is-geo-and-why-does-it-matter/',
      edit_url: 'http://localhost:8080/wp-admin/post.php?post=4&action=edit',
      status: 'publish',
      score: 86,
      grade: 'B' as const,
      issues: 2,
      findings: [
        {
          id: 'geo.structure',
          category: 'geo' as const,
          severity: 'info' as const,
          title: 'No comparison, listicle, or FAQ structure',
          message:
            'LLMs cite structured content far more than long-form prose. Even one section in one of these formats lifts your citation share.',
          fix: 'Add an FAQ block, a "Top N" list, or an "X vs Y" comparison anywhere in the post.',
          fixable: false,
          fix_meta: {},
        },
      ],
      internal_links_in: 1,
      internal_links_out: 3,
      word_count: 412,
      has_schema: true,
      modified: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    },
    {
      id: 5,
      title: 'Internal linking is the most underused SEO lever',
      url: 'http://localhost:8080/internal-linking-is-the-most-underused-seo-lever/',
      edit_url: 'http://localhost:8080/wp-admin/post.php?post=5&action=edit',
      status: 'publish',
      score: 92,
      grade: 'A' as const,
      issues: 0,
      findings: [],
      internal_links_in: 2,
      internal_links_out: 4,
      word_count: 658,
      has_schema: true,
      modified: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    },
    {
      id: 6,
      title: 'Schema markup explained for non-developers',
      url: 'http://localhost:8080/schema-markup-explained-for-non-developers/',
      edit_url: 'http://localhost:8080/wp-admin/post.php?post=6&action=edit',
      status: 'publish',
      score: 64,
      grade: 'D' as const,
      issues: 3,
      findings: [
        {
          id: 'content.thin',
          category: 'content' as const,
          severity: 'error' as const,
          title: 'Page is thin (17 words)',
          message:
            'Pages under 200 words are flagged as low-value by search engines and rarely cited by LLMs.',
          fix: 'Add at least 300-500 words of genuinely useful content. Cover what the reader is actually trying to learn.',
          fixable: false,
          fix_meta: {},
        },
        {
          id: 'links.orphan',
          category: 'links' as const,
          severity: 'error' as const,
          title: 'Orphan page — nothing links to it',
          message:
            'No other post on your site links here, so it rarely gets crawled or ranked. This is the highest-leverage fix on this list.',
          fix: 'Open Internal Links → find a matching suggestion → click Apply.',
          fixable: true,
          fix_meta: { action: 'orphan_link_in', post_id: 6 },
        },
        {
          id: 'meta.excerpt.missing',
          category: 'meta' as const,
          severity: 'warn' as const,
          title: 'No excerpt set',
          message:
            'WordPress auto-generates one from your first paragraph, but a hand-written excerpt makes a better SERP description and better social card.',
          fix: 'In the post editor, expand the Excerpt panel and write 1-2 sentences (120-160 chars).',
          fixable: false,
          fix_meta: {},
        },
      ],
      internal_links_in: 0,
      internal_links_out: 1,
      word_count: 17,
      has_schema: true,
      modified: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
    },
  ],
  linkSuggestions: [
    {
      from_id: 4,
      from_title: 'What is GEO and why does it matter?',
      from_url: '/what-is-geo/',
      to_id: 5,
      to_title: 'Internal linking is the most underused SEO lever',
      to_url: '/internal-linking/',
      similarity: 0.42,
      anchor: 'internal linking',
    },
    {
      from_id: 4,
      from_title: 'What is GEO and why does it matter?',
      from_url: '/what-is-geo/',
      to_id: 6,
      to_title: 'Schema markup explained for non-developers',
      to_url: '/schema-markup/',
      similarity: 0.38,
      anchor: 'schema markup',
    },
    {
      from_id: 5,
      from_title: 'Internal linking is the most underused SEO lever',
      from_url: '/internal-linking/',
      to_id: 6,
      to_title: 'Schema markup explained for non-developers',
      to_url: '/schema-markup/',
      similarity: 0.34,
      anchor: 'schema',
    },
  ],
  settings: {
    enable_schema: true,
    enable_internal_links: true,
    enable_faq_schema: true,
    enable_breadcrumbs: true,
    enable_organization: true,
    enable_open_graph: true,
    organization_name: 'Klyna SEO Suite — Test Site',
    organization_logo: '',
    twitter_handle: '@klynahq',
    internal_links_per_post: 5,
    internal_links_min_similarity: 0.15,
  },
};
