# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7cede999b6d21fcbcabf544952de3c48"
name = "Klyna Upsell"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_inventory,read_orders,read_products,write_discounts"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2026-07"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
