# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1eacc2bec267d1e592448ead6e5c2777"
name = "Klyna Capture"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,read_themes,write_customers"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
