api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "klyna-bundle-discount"
type = "function"
uid = "5761b43f-662f-d87b-e62f-31d5d1b6f10bbfba8e97"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
