# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ce967ef55bafcdeb9823498ffedb17c7"
name = "Klyna Wishlist"
handle = "klyna-wishlist"
application_url = "https://klyna-wishlist.vercel.app/app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://klyna-wishlist.vercel.app/auth/callback",
  "https://klyna-wishlist.vercel.app/auth/shopify/callback",
  "https://klyna-wishlist.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

[build]
automatically_update_urls_on_dev = false
