# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5562b3e17b36882181d43367a6f87631"
application_url = "https://example.com"
embedded = true
name = "Klyna Rewards"

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_customers,write_discounts"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
