# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "02ac921ec3c9f022d897a40a87015d96"
name = "Klyna Sticky Cart"
handle = "klyna-sticky-cart"
application_url = "https://klyna-sticky-cart.vercel.app/app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,read_products,write_metaobjects"

[auth]
redirect_urls = [
  "https://klyna-sticky-cart.vercel.app/auth/callback",
  "https://klyna-sticky-cart.vercel.app/auth/shopify/callback",
  "https://klyna-sticky-cart.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks/compliance"

[build]
automatically_update_urls_on_dev = false
