# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c62d723996fab365ffef98056499f368"
application_url = "https://example.com"
embedded = true
name = "Klyna Feed"

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,read_publications"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
