// Klyna Feed — feed renderers (Google Shopping XML + channel CSV).
//
// Both take the same array of resolved items (Record<FeedField, string>) and
// emit the channel's native format. XML uses the Google RSS 2.0 + g: namespace;
// CSV uses the shared Google-derived column set, which Meta/TikTok/Pinterest
// all accept.

import type { FeedField } from './types';
import { FEED_FIELD_ORDER } from './channels';

// XML-escape a text node value.
function xmlEscape(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

// Fields that live in the default RSS namespace (not g:) inside <item>.
const RSS_NATIVE: Partial<Record<FeedField, string>> = {
  id: 'g:id',
  title: 'title',
  description: 'description',
  link: 'link',
};

// Map a feed field onto its Google XML element name.
function xmlTag(field: FeedField): string {
  if (RSS_NATIVE[field]) return RSS_NATIVE[field]!;
  return `g:${field}`;
}

export interface RenderMeta {
  shop: string;
  feedName: string;
  language: string;
  generatedAt: string; // ISO
}

// Render a Google Shopping XML feed (RSS 2.0). additional_image_link repeats
// as multiple nodes per the spec rather than a comma-joined value.
export function renderXml(
  items: Record<FeedField, string>[],
  meta: RenderMeta,
): string {
  const lines: string[] = [];
  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push('<rss version="2.0" xmlns:g="http://base.google.com/ns/1.0">');
  lines.push('  <channel>');
  lines.push(`    <title>${xmlEscape(meta.feedName)}</title>`);
  lines.push(`    <link>https://${xmlEscape(meta.shop)}</link>`);
  lines.push(`    <description>Product feed generated by Klyna Feed for ${xmlEscape(meta.shop)}.</description>`);
  lines.push(`    <lastBuildDate>${xmlEscape(meta.generatedAt)}</lastBuildDate>`);

  for (const item of items) {
    lines.push('    <item>');
    for (const field of FEED_FIELD_ORDER) {
      const value = item[field];
      if (!value) continue;
      if (field === 'additional_image_link') {
        // Repeat the node for each extra image.
        for (const url of value.split(',').filter(Boolean)) {
          lines.push(`      <g:additional_image_link>${xmlEscape(url)}</g:additional_image_link>`);
        }
        continue;
      }
      const tag = xmlTag(field);
      lines.push(`      <${tag}>${xmlEscape(value)}</${tag}>`);
    }
    lines.push('    </item>');
  }

  lines.push('  </channel>');
  lines.push('</rss>');
  return lines.join('\n');
}

// CSV-quote a value (RFC 4180): wrap in quotes, double inner quotes.
function csvCell(value: string): string {
  if (value === '') return '';
  if (/[",\n\r]/.test(value)) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

// Render a CSV feed using the canonical column order. Meta/TikTok/Pinterest all
// ingest this header set (it's the Google spec column naming).
export function renderCsv(items: Record<FeedField, string>[]): string {
  const header = FEED_FIELD_ORDER.join(',');
  const rows = items.map((item) =>
    FEED_FIELD_ORDER.map((field) => csvCell(item[field] ?? '')).join(','),
  );
  return [header, ...rows].join('\n');
}

export { xmlEscape };
