# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6260327919ba89281d281c3f464968d4"
name = "Klyna SEO"
application_url = "https://klyna-seo.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,write_content,read_orders,read_products,write_products,read_themes,write_metaobjects,read_metaobjects"

[auth]
redirect_urls = [
  "https://klyna-seo.vercel.app/auth/callback",
  "https://klyna-seo.vercel.app/auth/shopify/callback",
  "https://klyna-seo.vercel.app/api/auth/callback",
  "https://klyna-seo.vercel.app/auth/login",
]
